---
title: DomainDrivenDesign.ir | Clean Code Mastery 2026
description: Clean Code Mastery workshop
logo: assets/images/Most-Influential-Computer-Programmers.jpg
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
---
