
title: DomainDrivenDesign.ir | Clean Code Mastery 2026
description: Clean Code Mastery workshop

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one